# format = """
# $username\
# $directory\
# $git_branch\
# $git_status\
# $fill\
# $c\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# $conda\
# $python\
# $time\n  \
# [󱞪](fg:iris) \
# """

add_newline = false

# A minimal left prompt
format = """$directory$character"""

# palette = "rose-pine-moon"
palette = "catppuccin_mocha"

right_format = "$hostname$git_branch$time$aws$cmd_duration$status"

command_timeout = 800
scan_timeout = 30

######  Rose pine palette settings start here  ######
#
# [directory]
# format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
# style = "bg:overlay fg:pine"
# truncation_length = 3
# truncation_symbol = "…/"
#
# [directory.substitutions]
# Documents = "󰈙"
# Downloads = " "
# Music = " "
# Pictures = " "
#
# [fill]
# style = "fg:overlay"
# symbol = " "
#
# [git_branch]
# format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
# style = "bg:overlay fg:foam"
# symbol = ""
#
# [git_status]
# disabled = false
# style = "bg:overlay fg:love"
# format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
# up_to_date = '[ ✓ ](bg:overlay fg:iris)'
# untracked = '[?\($count\)](bg:overlay fg:gold)'
# stashed = '[$](bg:overlay fg:iris)'
# modified = '[!\($count\)](bg:overlay fg:gold)'
# renamed = '[»\($count\)](bg:overlay fg:iris)'
# deleted = '[✘\($count\)](style)'
# staged = '[++\($count\)](bg:overlay fg:gold)'
# ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
# diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
# behind = '[⇣\(${count}\)](bg:overlay fg:rose)'
#
# [time]
# disabled = false
# format = "[](fg:overlay)[ $time 󰴈 ]($style)[](fg:overlay)"
# style = "bg:overlay fg:rose"
# time_format = "%I:%M%P"
# use_12hr = true
#
# [username]
# disabled = false
# format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay) "
# show_always = true
# style_root = "bg:overlay fg:iris"
# style_user = "bg:overlay fg:iris"
#
# # Languages
#
# [c]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = " "
#
# [elixir]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = " "
#
# [elm]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = " "
#
# [golang]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = " "
#
# [haskell]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = " "
#
# [java]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = " "
#
# [julia]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = " "
#
# [nodejs]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = "󰎙 "
#
# [nim]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = "󰆥 "
#
# [rust]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = ""
#
# [scala]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = " "
#
# [python]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
# disabled = false
# symbol = ' '
#
# [conda]
# style = "bg:overlay fg:pine"
# format = "[](fg:overlay)[$symbol$environment]($style)[](fg:overlay) "
# disabled = false
# symbol = '🅒 '
#
######  Rose pine palette settings end here  ######


###### Catpuccin settings start here ######
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vicmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
style = "bold mauve"

[git_status]
disabled = false
style = "bold overlay1"
format = '([$all_status$ahead_behind]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "✖${count}"
deleted = "✘${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "•${count}"
renamed = "»${count}"
staged = "+${count}"
stashed = "$"
untracked = "?${count}"
up_to_date = "✓"

[git_metrics]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[package]
disabled = true

[memory_usage]
disabled = true

[kubernetes]
disabled = true

[terraform]
disabled = true

[nix_shell]
disabled = true

[time]
disabled = false
format = "[$time ]($style)"
use_12hr = true
style = "bold overlay1"

[hostname]
ssh_only = true
format = "[$hostname ]($style)"
style = "bold overlay1"

[cmd_duration]
min_time = 700
show_milliseconds = true
format = "[$duration ]($style)"
style = "bold overlay1"

[status]
disabled = false
format = "[$symbol]($style) "
symbol = "✘"
style = "bold red"

[nodejs]
# Only show when a Node/Deno project is clearly detected
detect_files = ["package.json", "pnpm-lock.yaml", "yarn.lock", "deno.json", "deno.jsonc"]

[python]
# Only show in real Python projects
detect_files = ["pyproject.toml", "requirements.txt", ".python-version"]

[directory]
style = "bold lavender"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

[docker_context]
disabled = true

# [nodejs]
# format = '[󰎙 ](bold cyan)'

# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
